<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DLLA0593" ignored="0" name="Test" tests="2" failures="1" timestamp="28 Jan 2017 15:01:56 GMT" time="0.064" errors="0">
  <testcase name="add" time="0.012" classname="com.qait.training.ExampleProject.TestNgTest"/>
  <testcase name="divide" time="0.009" classname="com.qait.training.ExampleProject.TestNgTest">
    <failure type="java.lang.AssertionError" message="Value should be greater than 1. Denominator should be less than numerator expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Value should be greater than 1. Denominator should be less than numerator expected [true] but found [false]
	at com.qait.training.ExampleProject.TestNgTest.divide(TestNgTest.java:39)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- divide -->
</testsuite> <!-- Test -->
